# Сервис для вывода курса валют по запросу через HTTP


version: "3.9"
services:
  postgres:
    # БД PostgreSQL
    image: postgres:13.3
    environment:
      POSTGRES_DB: "exchange_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "very_difficult_password"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d exchange_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - exchange_rate

  get_exchange_rate:
    # Сервис создающий таблицу с курсами валют и заполняющий ее по расписанию
    # информацией, полученной от ЦБР
    build:
      context: get_exchange_rate
    environment:
      USER: "admin"
    restart: always
    networks:
      - exchange_rate
    depends_on:
      - postgres

  api:
    # Web-сервер, который будет выдавать курсы валют по запросам пользователей
    build:
      context: api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - get_exchange_rate
    networks:
      - exchange_rate

networks:
  exchange_rate:
    driver: bridge
